version: "3.5"

services:
    php-fpm:
        build: ./docker/php-fpm
        volumes:
            - ./:/opt/project/
        environment:
            APP_ENV: 'dev'
            APP_DEBUG: 1
        expose:
            - 9003
        links:
            - db
        depends_on:
            - db

    webserver:
        build: ./docker/nginx
        ports:
            - "8080:80"
        volumes:
            - ./:/opt/project/
        links:
            - php-fpm

    db:
        image: mysql:latest
        restart: always
        command: [ "--log_bin_trust_function_creators=1" ]
        ports:
            - "3346:3306"
        environment:
            MYSQL_DATABASE: 'test_db'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'admin'
            MYSQL_ROOT_PASSWORD: 'root'
